bsh1023 코드리뷰
wnsgml972/cppBasic pull request #17
Opened 2019-11-15 00:51 UTC by SoohanBae

- 함수명, 변수명이 이해 하게 쉽게 적혀 있는가?
- 함수내부에서 다른 함수로 분리가 가능한 부분이 있는가?
- 예외처리는 잘되어 있는가?

2019-11-15 01:31 UTC, wnsgml972 reviewed
아직 전체적으로 WhiteSpace 및 Naming 규칙이 통일되지 않은 것 같습니다.
Review할 내용이 너무 많아 한번에 다 하는 것은 힘들 것 같습니다.
기본적으로 말했던 내용을 다시 한번 꼼꼼하게 모두 확인하고, 다시 리뷰진행하는게 좋을 것 같습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Base.hpp
> +
생성자는 없는 상황일까요?

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Base.hpp
> +		virtual ~Base() {};
아무것도 하지 않는 소멸자라면 `virtual~Base() = default;`의 방식도 좋아보입니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Base.hpp
> +	private:
private: 밑에 변수가 없다면 지워주세요!

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Base.hpp
> +	bool Base<ElementType>::AddDataUsingStdInput(){
Add Data보다 Add Element라는 함수 이름이 더 좋아보입니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Base.hpp
> +		ElementType inputData;
마찬가지로 inputData가 아닌 inputElement로 수정부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/DoubleList.cpp
> +	DoubleListNode *listHead = {};
노말 포인터는 p라는 변수를 최초에 붙여주세요!
이 밑으로도 전부 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/DoubleList.h
> +
DoubleList는 템플릿 및 클래스로 구현이 안되어있네요?

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		ElementType data = {};
data보단 listElement라는 변수가 좀 더 좋아보입니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		ListNode<ElementType> *m_pHead;
클래스의 선언부는 추상화 수준에 따라 변수를 제일 아래로 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		bool AddData(const ElementType& data) override;
순수 가상함수를 오버라이딩한 함수들은 override 태그 뿐만 아니라 함수의 최초앞에 virtual도 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		~List();
Base 클래스의 소멸자에 virtual로 선언을 올바르게 하셨습니다.

해상 소멸자를 오버라이딩 했다는 뜻으로 `virtual ~List() override;`로 변경 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		bool DeleteData(const ElementType& data) override;
마찬가지로 변수명 수정 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +
마찬가지로 함수명 및 변수명 수정 부탁드립니다.
수정 시 위에 DeleteAllNode와 맞춰서 AddNode로 할지 Add Element로 하고 Delete와도 맞출지 고려부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		//�ߺ��˻�+ �����Ͱ� �� �ġ ã�Ƴ��
주석이 필요할 만큼 헷갈리는 부분이라면 주석보다는

`FindElementExceptDuplicate` 라는 함수로 만드는 게 좋을 것 같습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +	bool List<ElementType>::DeleteData(const ElementType& data) {
마찬가지로 명칭 수정 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		const List<ElementType>& original = static_cast<const List<ElementType>&>(right); //�ٿ�ĳ����
주석은 없어도 될 것 같습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Stack.cpp
> +	StackNode *stackHead = {};
p가 빠져있는 것 같습니다!

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Stack.h
> +	struct StackNode {
double list와 마찬가지로 스택은 템플릿 및 클래스로 구현되어있지 않습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +		~Vector();
소멸자에 virtual, override 추가 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +		bool DeleteData(const ElementType& data) override;
위와 마찬가지로 명칭 수정 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +		ElementType GetData(const int& index) const;
추상화 수준에 따라 변수가 아래 함수가 위로 순서 변경 부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +
이 함수 내에서 index를 뜻하는 int 값과 성공과 실패를 알려야 할 true, false의 변수가 필요해보입니다.

NOT_FOUND_INDEX를 반환하는 방식이 아닌, std::optional을 사용하면 더욱 좋을 것 같습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +
Index의 범위에 대한 예외처리가 있으면 더욱 좋을 것 같습니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/VectorManager.hpp
> +namespace manager {
전체적으로 위에서 드렸던 내용 바탕으로 아래도 수정부탁드립니다.

2019-11-15 01:31 UTC, wnsgml972 commented on cppStudy/VectorManager.hpp
> +namespace manager {
전체적으로 White Space에 대한 정리가 되어있지 않은 것 같습니다.
저번에 부탁드렸던데로 그것도 정리 부탁드립니다.

2019-11-15 08:30 UTC, SoohanBae commented on cppStudy/DoubleList.h
> +
'C-Style로 구현 (클래스 사용말고, 구조체와 함수 사용)' 라고 적혀 있어서 클래스로 구현 하지 않았습니다. 제가 잘못 이해 했나요?

2019-11-18 00:00 UTC, wnsgml972 commented on cppStudy/DoubleList.h
> +
아하 그게 최초 과제였는데 한 솔루션에 있는거였군요!! 그러면 C-Style 방식은 유지되어도 좋을 것 같습니다!

2019-11-19 00:37 UTC, SoohanBae commented on cppStudy/VectorManager.hpp
> +namespace manager {
코드 리팩토링후 푸시 했습니다!, 확인부탁드립니다.

2019-11-19 04:41 UTC, wnsgml972 requested changes
2차 리뷰!

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/DoubleList.cpp
> +			return;
사용자가 함수를 잘못사용했을 경우 ASSERT를 통해 알려주는 것이 좋은 디버깅 방법이 될 수 있습니다.
ASSERT(0);

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		virtual List<ElementType>& operator=(List<ElementType>& right);
오버라이딩이 아닌 오버로딩으로서의 사용만 원할 경우 virtual을 뺀 후, 추상화 수준에 따라 함수를 제일 아래로 위치시키는 것이 좋아보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/List.hpp
> +		ListNode<ElementType>* GetHeadPointer() const;
혹시 Head Pointer의 상수화를 원하는 것이면 `const ListNode<ElementType>*`, ListNode<ElementType> const *`를 사용하는 것이 좋아보입니다.
두 개의 사용이 다 필요한경우면, GetSafeHeadPointer와 GetRawHeadPointer를 2개로 나누어 사용하는 방법도 생각해볼 수 있습니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +		if (!pVectorListOptional.has_value()) {
여기서 value의 valid도 같이 하면 좋을 것 같습니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			bool returns = AddVectorListFromText(lineText);
변수명 수정이 필요해보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			return false;
중간에 끝내버리는 경우가 있기 때문에, 이 행위에 대한 추가 설명이 함수 이름에 있으면 좋을 것 같습니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +	bool ElementManager<ElementType>::AddVectorListFromText(std::wstring text){
const std::wstring& text

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +	bool ElementManager<ElementType>::AddVectorListFromText(std::wstring text){
로 하는 것이 좋아보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
_함수들은 비표준 함수입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
https://github.com/wnsgml972/queryparse/blob/master/src/queryparse/StringConverter.hpp

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
std::to_integer를 사용하는 것이 좋아보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +		virtual Vector<ElementType>& operator=(Vector<ElementType>& right);
위와 마찬가지로 수정하는 것이 좋을 것 같습니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +		free(m_pElement);
Safe Delete 방식으로 이렇게 하는 것이 더 좋아보입니다.
`if(m_pElement) free(m_pElement);`

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +	bool Vector<ElementType>::AddElement(const ElementType& element) {
중복 데이터는 못 넣는 행위를 하니, 함수의 이름에 변경이 필요해보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Vector.hpp
> +			return false;
없는 데이터는 못 지우려고 하는 것은 밖에서 잘못 사용한 행위 -> ASSERT(0); 디버깅을 도와주는 것이 좋아보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/List.hpp
> +	bool List<ElementType>::AddElement(const ElementType& element) {
마찬가지로 제일 바깥의 함수의 이름에 변경이 필요해보입니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +		~ElementManager();
혹시 모르니까 소멸자는 항상 virtual로 하는 것이 좋습니다.

2019-11-19 04:41 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +
bool로 예외처리 한다는 것은 성공과 실패를 가지고, 그 예외처리의 책임을 다음 함수에게 넘기는 것입니다.
사용자에 값에 따라 어쩔 수 없이 true, false가 있는 것은 그렇게 하는 것이 맞지만 항상 성공해야만 하는 것은 bool로 처리하여 다음 함수에게 예외처리의 책임을 던지는 것이 아니라, ASSERT(0) 등 으로 알려주어 그 함수에서 완전하게 책임을 처리해주는 것이 맞습니다. void로 하고 api 사용자에게 그 함수를 무조건 수정하도록 유도하는 것이 좋아보입니다.

2019-11-20 00:47 UTC, SoohanBae commented on cppStudy/List.hpp
> +		virtual List<ElementType>& operator=(List<ElementType>& right);
위치 조정시켰습니다.

2019-11-20 00:48 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +	bool ElementManager<ElementType>::AddVectorListFromText(std::wstring text){
변경 했습니다.

2019-11-20 01:05 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
우선 함수에서 제공하는 형태가 int, long, double입니다. 이외의 데이터 타입은 지원하지 않으며 이에 대해서 함수에 명시도 필요해 보입니다. 우선 int형 자료형만 지원하는 함수로 바꾼뒤 함수명도 수정하도록 하겠습니다.

2019-11-20 02:06 UTC, SoohanBae commented on cppStudy/DoubleList.cpp
> +			return;
Tail 함수에도 적용햇습니다!

2019-11-20 02:08 UTC, SoohanBae commented on cppStudy/List.hpp
> +		ListNode<ElementType>* GetHeadPointer() const;
확인해보니 Head Pointer의 상수화가 필요하지 않는 함수이네요

2019-11-20 02:11 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +			bool returns = AddVectorListFromText(lineText);
isLineTextValid 로 변경 했습니다.
cim에서는 bool 함수에 is를 붙이나요?

2019-11-20 02:14 UTC, SoohanBae commented on cppStudy/Vector.hpp
> +		free(m_pElement);
구현했습니다.

2019-11-20 02:16 UTC, SoohanBae commented on cppStudy/Vector.hpp
> +			return false;
assert 추가했습니다.

2019-11-20 02:33 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +
전체적으로 assert(0)을 적극 이용해 보았습니다.

2019-11-20 03:03 UTC, SoohanBae commented on cppStudy/Vector.hpp
> +	bool Vector<ElementType>::AddElement(const ElementType& element) {
AddNotDuplicationElement 변경했습니다.

2019-11-20 03:06 UTC, SoohanBae commented on cppStudy/Vector.hpp
> +	bool Vector<ElementType>::AddElement(const ElementType& element) {
AddNonDuplicateElement 로 재변경 했습니다.

2019-11-20 03:30 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +			return false;
bool ElementManager<ElementType>::AddVectorListForText(const std::wstring& text){ 
		//텍스트 형식에 맞는 'text'를 'vector list' 에 추가, 제가 표현하고 싶은게 함수명으로 드러났을까요?

2019-11-20 05:36 UTC, SoohanBae commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
현재 이 함수는 일부 자료형의 변환만 지원합니다. 이를 명시하기 위한 좋은 방법이 없을까요?

2019-11-20 06:12 UTC, wnsgml972 commented on cppStudy/Manager.hpp
> +			element = _wtoi(elementText);
나머지 else에 대한 예외처리만 추가하시면 될 것 같습니다.

2019-11-20 06:13 UTC, wnsgml972 reviewed
else에 대한 추가처리만 구현하시면 될 것 같습니다.

현재 지원할 수 없는 기능에 대한 기능을 사용하는 사용자에게 주는 정보를 추가하는 것

2019-11-20 06:29 UTC, wnsgml972 requested changes
구현한 기능들에 대한 검증이 필요해보입니다.

2019-11-21 05:04 UTC, wnsgml972 commented
고생하셨습니다!  

MFC 과제 UI 입힌 프로젝트 진행하기 (필수 구현 기능만 지킨 체 원하는 UI로 프로젝트를 진행하시면 될 것 같습니다.)
https://github.com/wnsgml972/MFCPhoneBook

2019-11-21 05:05 UTC, merged